[package]
name = "rawsliced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = {version = "1.6.0", optional = true }

[features]
default = ["rayon"]
rayon = ["std", "dep:rayon"]
std = []
